services:
  db: # DB 서비스
    image: mysql:latest
    container_name: gwon-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - global_network

  cloudflare: # 클라우드플레어 터널
    image: cloudflare/cloudflared:latest
    container_name: gwon-cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN} 
    networks:
      - global_network

  frontend: # 들여쓰기 수정됨
    restart: always
    container_name: gwon-frontend
    build: ./frontend
    networks:
      - global_network
    
  backend: # 들여쓰기 수정됨
    restart: always
    container_name: gwon-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data # 루트 data 폴더를 컨테이너 /data에 매핑
    networks:
      - global_network
    depends_on:
      - db

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: gwon-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data # 볼륨 경로 명시
    networks:
      - global_network

networks:
  global_network:
    external: true