version: '3.8'
services:



  app:
    build: .
    ports:
      - "80:8080" #외부 브라우저의 80포트를 Docker를 통해 8080포트로 전달한다
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gwondb
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: