// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdBj0xKxlnWZPy3kSjgKFP8RcT6K7Ye9o',
    appId: '1:764359091020:web:5949541ec2681a937ba5e9',
    messagingSenderId: '764359091020',
    projectId: 'gwon-5198b',
    authDomain: 'gwon-5198b.firebaseapp.com',
    storageBucket: 'gwon-5198b.firebasestorage.app',
    measurementId: 'G-R7L0Q6H469',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jmLOe7t2BWlBAqDIsq8L4RWTCa03zGI',
    appId: '1:764359091020:android:53ffd277612f68947ba5e9',
    messagingSenderId: '764359091020',
    projectId: 'gwon-5198b',
    storageBucket: 'gwon-5198b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFE3tSt5btTu-cty4OOGDSCYYyAojf3Ac',
    appId: '1:764359091020:ios:8080309e8a7a7ae07ba5e9',
    messagingSenderId: '764359091020',
    projectId: 'gwon-5198b',
    storageBucket: 'gwon-5198b.firebasestorage.app',
    iosBundleId: 'com.example.gwon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFE3tSt5btTu-cty4OOGDSCYYyAojf3Ac',
    appId: '1:764359091020:ios:8080309e8a7a7ae07ba5e9',
    messagingSenderId: '764359091020',
    projectId: 'gwon-5198b',
    storageBucket: 'gwon-5198b.firebasestorage.app',
    iosBundleId: 'com.example.gwon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdBj0xKxlnWZPy3kSjgKFP8RcT6K7Ye9o',
    appId: '1:764359091020:web:3a66f46273dc84e87ba5e9',
    messagingSenderId: '764359091020',
    projectId: 'gwon-5198b',
    authDomain: 'gwon-5198b.firebaseapp.com',
    storageBucket: 'gwon-5198b.firebasestorage.app',
    measurementId: 'G-3FPLMN520S',
  );
}
