server:
  name: gwon
  port: 8080

spring:
  
  datasource:
    password: gwondb
    url: jdbc:mysql://db:3306/gwondb
    username: gwon
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


