name : Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 접속 및 docker-compose up합니다!!!!!
        uses: appleboy/ssh-action@v1.0.0
        
        with:
          port: 22
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_KEY }}
          username: ${{ secrets.SERVER_USER }}
          script: |
            cd ~/gwon
            git pull

            cd backend
            chmod +x ./gradlew
            ./gradlew build -x test
            ls -la build/libs/
            cd ..  # 다시 루트로 돌아가기 좀
            
            docker compose build --no-cache
            docker compose up -d
            docker compose restart nginx

